---
title: "Reactにおけるエラー処理react-error-boundaryで楽々エラー処理をしよう！"
emoji: "📖"
type: "tech"
topics: []
published: false
---

こんにちは、@nerusanです。

今回は、Reactにおけるエラー処理の話をします。

初めに、今回紹介する内容は、Kent C. Dodds氏がまとめた資料を参考に記述しております。

https://kentcdodds.com/blog/use-react-error-boundary-to-handle-errors-in-react

ウェブページを見ている時、通信エラーや間違ったリクエストした際は、例外やエラーが発生します。
それをもとに、エラーの旨をユーザーに知らせて、「ホームに戻る」や、「時間をおいてリロードしてください」など、次の手立てをユーザに示してあげることが大事になります。これをエラー処理と言います。

ここで、例外がスローされた時の処理を考えます。
なじみのあるtry/catchを利用して、エラーを表示する方法を考えます。

```ts
import * as React from 'react'
import ReactDOM from 'react-dom'

function ErrorFallback({error}) {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre style={{color: 'red'}}>{error.message}</pre>
    </div>
  )
}

function Greeting({subject}) {
  // 例外のスロー
  throw new Error();
}

function Farewell({subject}) {
  // 未定義の関数呼び出し
  return <div>Goodbye {toUpperCase()}</div>
}

function App() {
  try {
    return (
      <div>
        <Greeting />
        <Farewell />
      </div>
    )
  } catch (error) {
    return <ErrorFallback error={error} />
  }
}

ReactDOM.render(<App />, document.getElementById('root'))
```

残念ながら、これはうまくいきません。それは、GreetingとFarewellを呼び出しているのが私たちではないからです。Reactがこれらの関数を呼び出すのです。JSXでそれらを使用する場合、それらの関数を型としてReactの要素を作成しているだけです。Reactに「アプリがレンダリングされたら、呼び出す必要のあるコンポーネントはこれだ」と伝えているのです。しかし、実際にそれらをtry/catchで呼び出しているわけではないので、動作しません。

それを簡単解決するライブラリとして、ライブラリreact-error-boundaryを紹介します。

https://github.com/bvaughn/react-error-boundary#installation

# どこが便利？
* 一度定義するだけOK
	* 都度try/catchなどを記述する必要がない
* 意図しない例外にも対応できる
	* 意図しない例外が起きても対応できオル


# 使ってみよう

```ts:app.tsx
import type { AppProps } from 'next/app';
import { ErrorBoundary, FallbackProps } from 'react-error-boundary';
import apolloClient from '@/libs/apollo';

// エラー時に表示するコンポーネント
const ErrorFallback = ({ error }: FallbackProps) => {
  return (
    <div
      className="flex flex-col justify-center items-center w-screen h-screen text-red-500"
      role="alert"
    >
      <h2 className="text-lg font-semibold">問題が発生しました。</h2>
      <p>{error.message}</p>
      <button
        className="mt-4"
        onClick={() => window.location.assign(window.location.origin)}
      >
        ホームへ戻る
      </button>
    </div>
  );
};

// エラーが起きる範囲に対してErrorBoundaryコンポーネントをラッピング
// 今回はルートに対してラッピング
function App({ Component, pageProps }: AppProps) {
  return (
    <ErrorBoundary FallbackComponent={ErrorFallback}>
      <ApolloProvider client={apolloClient}>
        <Component {...pageProps} />
      </ApolloProvider>
    </ErrorBoundary>
  );
};

export default App;
```